server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: springboot
spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  application:
    name: spring-data-jpa-complex-object
#  datasource:
#    url: jdbc:h2:file:C:/Users/mf11475/customerdb #by defualt it will be test, you can create a folder as needed in root locn.
#    driverClassName: org.h2.Driver
#    username: sa
#    password: sa
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    driver-class-name: oracle.jdbc.OracleDriver
    username: system
    password: root
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always

#  CREATE USER system IDENTIFIED BY root;
#  GRANT CONNECT, RESOURCE TO system;
