-- ORACLE-COMPATIBLE INSERTS (GROUPED AT TOP)
-- CLASSES (Oracle-compatible multi-row insert)
INSERT ALL
  INTO classroom (id, name) VALUES (1, 'Class 1')
  INTO classroom (id, name) VALUES (2, 'Class 2')
  INTO classroom (id, name) VALUES (3, 'Class 3')
  INTO classroom (id, name) VALUES (4, 'Class 4')
  INTO classroom (id, name) VALUES (5, 'Class 5')
  INTO classroom (id, name) VALUES (6, 'Class 6')
  INTO classroom (id, name) VALUES (7, 'Class 7')
  INTO classroom (id, name) VALUES (8, 'Class 8')
  INTO classroom (id, name) VALUES (9, 'Class 9')
  INTO classroom (id, name) VALUES (10, 'Class 10')
SELECT * FROM DUAL;

-- SUBJECTS/COURSES (Oracle-compatible multi-row insert)
INSERT ALL
  INTO course (id, title) VALUES (1, 'English')
  INTO course (id, title) VALUES (2, 'Hindi')
  INTO course (id, title) VALUES (3, 'Telugu')
  INTO course (id, title) VALUES (4, 'Social')
  INTO course (id, title) VALUES (5, 'Science')
  INTO course (id, title) VALUES (6, 'Maths')
SELECT * FROM DUAL;

-- TEACHERS (Oracle-compatible multi-row insert, 60 records)
INSERT ALL
  INTO teacher (id, name) VALUES (1, 'Alice Johnson')
  INTO teacher (id, name) VALUES (2, 'Bob Smith')
  INTO teacher (id, name) VALUES (3, 'Carol Lee')
  INTO teacher (id, name) VALUES (4, 'David Kim')
  INTO teacher (id, name) VALUES (5, 'Eva Brown')
  INTO teacher (id, name) VALUES (6, 'Frank White')
  INTO teacher (id, name) VALUES (7, 'Grace Green')
  INTO teacher (id, name) VALUES (8, 'Henry Black')
  INTO teacher (id, name) VALUES (9, 'Ivy Young')
  INTO teacher (id, name) VALUES (10, 'Jack King')
  INTO teacher (id, name) VALUES (11, 'Kathy Hall')
  INTO teacher (id, name) VALUES (12, 'Leo Scott')
  INTO teacher (id, name) VALUES (13, 'Mona Adams')
  INTO teacher (id, name) VALUES (14, 'Nina Clark')
  INTO teacher (id, name) VALUES (15, 'Oscar Lewis')
  INTO teacher (id, name) VALUES (16, 'Paul Walker')
  INTO teacher (id, name) VALUES (17, 'Quinn Allen')
  INTO teacher (id, name) VALUES (18, 'Rita Baker')
  INTO teacher (id, name) VALUES (19, 'Sam Carter')
  INTO teacher (id, name) VALUES (20, 'Tina Davis')
  INTO teacher (id, name) VALUES (21, 'Uma Evans')
  INTO teacher (id, name) VALUES (22, 'Vera Foster')
  INTO teacher (id, name) VALUES (23, 'Will Harris')
  INTO teacher (id, name) VALUES (24, 'Xena James')
  INTO teacher (id, name) VALUES (25, 'Yuri Kelly')
  INTO teacher (id, name) VALUES (26, 'Zane Lopez')
  INTO teacher (id, name) VALUES (27, 'Amy Moore')
  INTO teacher (id, name) VALUES (28, 'Ben Nelson')
  INTO teacher (id, name) VALUES (29, 'Cody Ortiz')
  INTO teacher (id, name) VALUES (30, 'Dina Perez')
  INTO teacher (id, name) VALUES (31, 'Eli Reed')
  INTO teacher (id, name) VALUES (32, 'Fay Shaw')
  INTO teacher (id, name) VALUES (33, 'Gus Turner')
  INTO teacher (id, name) VALUES (34, 'Hope Underwood')
  INTO teacher (id, name) VALUES (35, 'Ian Vincent')
  INTO teacher (id, name) VALUES (36, 'Jill Ward')
  INTO teacher (id, name) VALUES (37, 'Kyle Xu')
  INTO teacher (id, name) VALUES (38, 'Lara Young')
  INTO teacher (id, name) VALUES (39, 'Mick Zane')
  INTO teacher (id, name) VALUES (40, 'Nora Abbott')
  INTO teacher (id, name) VALUES (41, 'Omar Brooks')
  INTO teacher (id, name) VALUES (42, 'Pia Cruz')
  INTO teacher (id, name) VALUES (43, 'Qing Du')
  INTO teacher (id, name) VALUES (44, 'Rex Fox')
  INTO teacher (id, name) VALUES (45, 'Sia Grant')
  INTO teacher (id, name) VALUES (46, 'Tom Hill')
  INTO teacher (id, name) VALUES (47, 'Usha Iyer')
  INTO teacher (id, name) VALUES (48, 'Vic Jones')
  INTO teacher (id, name) VALUES (49, 'Walt Kim')
  INTO teacher (id, name) VALUES (50, 'Yana Lin')
  INTO teacher (id, name) VALUES (51, 'Zara Patel')
  INTO teacher (id, name) VALUES (52, 'Rohan Mehta')
  INTO teacher (id, name) VALUES (53, 'Priya Singh')
  INTO teacher (id, name) VALUES (54, 'Anil Kumar')
  INTO teacher (id, name) VALUES (55, 'Meena Rao')
  INTO teacher (id, name) VALUES (56, 'Deepak Shah')
  INTO teacher (id, name) VALUES (57, 'Sonal Jain')
  INTO teacher (id, name) VALUES (58, 'Vikas Gupta')
  INTO teacher (id, name) VALUES (59, 'Ritu Verma')
  INTO teacher (id, name) VALUES (60, 'Amit Sinha')
SELECT * FROM DUAL;

-- STUDENTS: Records 101–200 (Oracle-compatible multi-row insert)
INSERT ALL
  INTO student (id, name, classroom_id) VALUES (101, 'Student_101', 2)
  INTO student (id, name, classroom_id) VALUES (102, 'Student_102', 2)
  INTO student (id, name, classroom_id) VALUES (103, 'Student_103', 2)
  INTO student (id, name, classroom_id) VALUES (104, 'Student_104', 2)
  INTO student (id, name, classroom_id) VALUES (105, 'Student_105', 2)
  INTO student (id, name, classroom_id) VALUES (106, 'Student_106', 2)
  INTO student (id, name, classroom_id) VALUES (107, 'Student_107', 2)
  INTO student (id, name, classroom_id) VALUES (108, 'Student_108', 2)
  INTO student (id, name, classroom_id) VALUES (109, 'Student_109', 2)
  INTO student (id, name, classroom_id) VALUES (110, 'Student_110', 2)
  INTO student (id, name, classroom_id) VALUES (111, 'Student_111', 2)
  INTO student (id, name, classroom_id) VALUES (112, 'Student_112', 2)
  INTO student (id, name, classroom_id) VALUES (113, 'Student_113', 2)
  INTO student (id, name, classroom_id) VALUES (114, 'Student_114', 2)
  INTO student (id, name, classroom_id) VALUES (115, 'Student_115', 2)
  INTO student (id, name, classroom_id) VALUES (116, 'Student_116', 2)
  INTO student (id, name, classroom_id) VALUES (117, 'Student_117', 2)
  INTO student (id, name, classroom_id) VALUES (118, 'Student_118', 2)
  INTO student (id, name, classroom_id) VALUES (119, 'Student_119', 2)
  INTO student (id, name, classroom_id) VALUES (120, 'Student_120', 2)
  INTO student (id, name, classroom_id) VALUES (121, 'Student_121', 2)
  INTO student (id, name, classroom_id) VALUES (122, 'Student_122', 2)
  INTO student (id, name, classroom_id) VALUES (123, 'Student_123', 2)
  INTO student (id, name, classroom_id) VALUES (124, 'Student_124', 2)
  INTO student (id, name, classroom_id) VALUES (125, 'Student_125', 2)
  INTO student (id, name, classroom_id) VALUES (126, 'Student_126', 2)
  INTO student (id, name, classroom_id) VALUES (127, 'Student_127', 2)
  INTO student (id, name, classroom_id) VALUES (128, 'Student_128', 2)
  INTO student (id, name, classroom_id) VALUES (129, 'Student_129', 2)
  INTO student (id, name, classroom_id) VALUES (130, 'Student_130', 2)
  INTO student (id, name, classroom_id) VALUES (131, 'Student_131', 2)
  INTO student (id, name, classroom_id) VALUES (132, 'Student_132', 2)
  INTO student (id, name, classroom_id) VALUES (133, 'Student_133', 2)
  INTO student (id, name, classroom_id) VALUES (134, 'Student_134', 2)
  INTO student (id, name, classroom_id) VALUES (135, 'Student_135', 2)
  INTO student (id, name, classroom_id) VALUES (136, 'Student_136', 2)
  INTO student (id, name, classroom_id) VALUES (137, 'Student_137', 2)
  INTO student (id, name, classroom_id) VALUES (138, 'Student_138', 2)
  INTO student (id, name, classroom_id) VALUES (139, 'Student_139', 2)
  INTO student (id, name, classroom_id) VALUES (140, 'Student_140', 2)
  INTO student (id, name, classroom_id) VALUES (141, 'Student_141', 2)
  INTO student (id, name, classroom_id) VALUES (142, 'Student_142', 2)
  INTO student (id, name, classroom_id) VALUES (143, 'Student_143', 2)
  INTO student (id, name, classroom_id) VALUES (144, 'Student_144', 2)
  INTO student (id, name, classroom_id) VALUES (145, 'Student_145', 2)
  INTO student (id, name, classroom_id) VALUES (146, 'Student_146', 2)
  INTO student (id, name, classroom_id) VALUES (147, 'Student_147', 2)
  INTO student (id, name, classroom_id) VALUES (148, 'Student_148', 2)
  INTO student (id, name, classroom_id) VALUES (149, 'Student_149', 2)
  INTO student (id, name, classroom_id) VALUES (150, 'Student_150', 2)
  INTO student (id, name, classroom_id) VALUES (151, 'Student_151', 2)
  INTO student (id, name, classroom_id) VALUES (152, 'Student_152', 2)
  INTO student (id, name, classroom_id) VALUES (153, 'Student_153', 2)
  INTO student (id, name, classroom_id) VALUES (154, 'Student_154', 2)
  INTO student (id, name, classroom_id) VALUES (155, 'Student_155', 2)
  INTO student (id, name, classroom_id) VALUES (156, 'Student_156', 2)
  INTO student (id, name, classroom_id) VALUES (157, 'Student_157', 2)
  INTO student (id, name, classroom_id) VALUES (158, 'Student_158', 2)
  INTO student (id, name, classroom_id) VALUES (159, 'Student_159', 2)
  INTO student (id, name, classroom_id) VALUES (160, 'Student_160', 2)
  INTO student (id, name, classroom_id) VALUES (161, 'Student_161', 2)
  INTO student (id, name, classroom_id) VALUES (162, 'Student_162', 2)
  INTO student (id, name, classroom_id) VALUES (163, 'Student_163', 2)
  INTO student (id, name, classroom_id) VALUES (164, 'Student_164', 2)
  INTO student (id, name, classroom_id) VALUES (165, 'Student_165', 2)
  INTO student (id, name, classroom_id) VALUES (166, 'Student_166', 2)
  INTO student (id, name, classroom_id) VALUES (167, 'Student_167', 2)
  INTO student (id, name, classroom_id) VALUES (168, 'Student_168', 2)
  INTO student (id, name, classroom_id) VALUES (169, 'Student_169', 2)
  INTO student (id, name, classroom_id) VALUES (170, 'Student_170', 2)
  INTO student (id, name, classroom_id) VALUES (171, 'Student_171', 2)
  INTO student (id, name, classroom_id) VALUES (172, 'Student_172', 2)
  INTO student (id, name, classroom_id) VALUES (173, 'Student_173', 2)
  INTO student (id, name, classroom_id) VALUES (174, 'Student_174', 2)
  INTO student (id, name, classroom_id) VALUES (175, 'Student_175', 2)
  INTO student (id, name, classroom_id) VALUES (176, 'Student_176', 2)
  INTO student (id, name, classroom_id) VALUES (177, 'Student_177', 2)
  INTO student (id, name, classroom_id) VALUES (178, 'Student_178', 2)
  INTO student (id, name, classroom_id) VALUES (179, 'Student_179', 2)
  INTO student (id, name, classroom_id) VALUES (180, 'Student_180', 2)
  INTO student (id, name, classroom_id) VALUES (181, 'Student_181', 2)
  INTO student (id, name, classroom_id) VALUES (182, 'Student_182', 2)
  INTO student (id, name, classroom_id) VALUES (183, 'Student_183', 2)
  INTO student (id, name, classroom_id) VALUES (184, 'Student_184', 2)
  INTO student (id, name, classroom_id) VALUES (185, 'Student_185', 2)
  INTO student (id, name, classroom_id) VALUES (186, 'Student_186', 2)
  INTO student (id, name, classroom_id) VALUES (187, 'Student_187', 2)
  INTO student (id, name, classroom_id) VALUES (188, 'Student_188', 2)
  INTO student (id, name, classroom_id) VALUES (189, 'Student_189', 2)
  INTO student (id, name, classroom_id) VALUES (190, 'Student_190', 2)
  INTO student (id, name, classroom_id) VALUES (191, 'Student_191', 2)
  INTO student (id, name, classroom_id) VALUES (192, 'Student_192', 2)
  INTO student (id, name, classroom_id) VALUES (193, 'Student_193', 2)
  INTO student (id, name, classroom_id) VALUES (194, 'Student_194', 2)
  INTO student (id, name, classroom_id) VALUES (195, 'Student_195', 2)
  INTO student (id, name, classroom_id) VALUES (196, 'Student_196', 2)
  INTO student (id, name, classroom_id) VALUES (197, 'Student_197', 2)
  INTO student (id, name, classroom_id) VALUES (198, 'Student_198', 2)
  INTO student (id, name, classroom_id) VALUES (199, 'Student_199', 2)
  INTO student (id, name, classroom_id) VALUES (200, 'Student_200', 2)
SELECT * FROM DUAL;

-- STUDENTS: First 100 records (Oracle-compatible multi-row insert)
INSERT ALL
  INTO student (id, name, classroom_id) VALUES (1, 'Student_1', 1)
  INTO student (id, name, classroom_id) VALUES (2, 'Student_2', 1)
  INTO student (id, name, classroom_id) VALUES (3, 'Student_3', 1)
  INTO student (id, name, classroom_id) VALUES (4, 'Student_4', 1)
  INTO student (id, name, classroom_id) VALUES (5, 'Student_5', 1)
  INTO student (id, name, classroom_id) VALUES (6, 'Student_6', 1)
  INTO student (id, name, classroom_id) VALUES (7, 'Student_7', 1)
  INTO student (id, name, classroom_id) VALUES (8, 'Student_8', 1)
  INTO student (id, name, classroom_id) VALUES (9, 'Student_9', 1)
  INTO student (id, name, classroom_id) VALUES (10, 'Student_10', 1)
  INTO student (id, name, classroom_id) VALUES (11, 'Student_11', 1)
  INTO student (id, name, classroom_id) VALUES (12, 'Student_12', 1)
  INTO student (id, name, classroom_id) VALUES (13, 'Student_13', 1)
  INTO student (id, name, classroom_id) VALUES (14, 'Student_14', 1)
  INTO student (id, name, classroom_id) VALUES (15, 'Student_15', 1)
  INTO student (id, name, classroom_id) VALUES (16, 'Student_16', 1)
  INTO student (id, name, classroom_id) VALUES (17, 'Student_17', 1)
  INTO student (id, name, classroom_id) VALUES (18, 'Student_18', 1)
  INTO student (id, name, classroom_id) VALUES (19, 'Student_19', 1)
  INTO student (id, name, classroom_id) VALUES (20, 'Student_20', 1)
  INTO student (id, name, classroom_id) VALUES (21, 'Student_21', 1)
  INTO student (id, name, classroom_id) VALUES (22, 'Student_22', 1)
  INTO student (id, name, classroom_id) VALUES (23, 'Student_23', 1)
  INTO student (id, name, classroom_id) VALUES (24, 'Student_24', 1)
  INTO student (id, name, classroom_id) VALUES (25, 'Student_25', 1)
  INTO student (id, name, classroom_id) VALUES (26, 'Student_26', 1)
  INTO student (id, name, classroom_id) VALUES (27, 'Student_27', 1)
  INTO student (id, name, classroom_id) VALUES (28, 'Student_28', 1)
  INTO student (id, name, classroom_id) VALUES (29, 'Student_29', 1)
  INTO student (id, name, classroom_id) VALUES (30, 'Student_30', 1)
  INTO student (id, name, classroom_id) VALUES (31, 'Student_31', 1)
  INTO student (id, name, classroom_id) VALUES (32, 'Student_32', 1)
  INTO student (id, name, classroom_id) VALUES (33, 'Student_33', 1)
  INTO student (id, name, classroom_id) VALUES (34, 'Student_34', 1)
  INTO student (id, name, classroom_id) VALUES (35, 'Student_35', 1)
  INTO student (id, name, classroom_id) VALUES (36, 'Student_36', 1)
  INTO student (id, name, classroom_id) VALUES (37, 'Student_37', 1)
  INTO student (id, name, classroom_id) VALUES (38, 'Student_38', 1)
  INTO student (id, name, classroom_id) VALUES (39, 'Student_39', 1)
  INTO student (id, name, classroom_id) VALUES (40, 'Student_40', 1)
  INTO student (id, name, classroom_id) VALUES (41, 'Student_41', 1)
  INTO student (id, name, classroom_id) VALUES (42, 'Student_42', 1)
  INTO student (id, name, classroom_id) VALUES (43, 'Student_43', 1)
  INTO student (id, name, classroom_id) VALUES (44, 'Student_44', 1)
  INTO student (id, name, classroom_id) VALUES (45, 'Student_45', 1)
  INTO student (id, name, classroom_id) VALUES (46, 'Student_46', 1)
  INTO student (id, name, classroom_id) VALUES (47, 'Student_47', 1)
  INTO student (id, name, classroom_id) VALUES (48, 'Student_48', 1)
  INTO student (id, name, classroom_id) VALUES (49, 'Student_49', 1)
  INTO student (id, name, classroom_id) VALUES (50, 'Student_50', 1)
  INTO student (id, name, classroom_id) VALUES (51, 'Student_51', 1)
  INTO student (id, name, classroom_id) VALUES (52, 'Student_52', 1)
  INTO student (id, name, classroom_id) VALUES (53, 'Student_53', 1)
  INTO student (id, name, classroom_id) VALUES (54, 'Student_54', 1)
  INTO student (id, name, classroom_id) VALUES (55, 'Student_55', 1)
  INTO student (id, name, classroom_id) VALUES (56, 'Student_56', 1)
  INTO student (id, name, classroom_id) VALUES (57, 'Student_57', 1)
  INTO student (id, name, classroom_id) VALUES (58, 'Student_58', 1)
  INTO student (id, name, classroom_id) VALUES (59, 'Student_59', 1)
  INTO student (id, name, classroom_id) VALUES (60, 'Student_60', 1)
  INTO student (id, name, classroom_id) VALUES (61, 'Student_61', 1)
  INTO student (id, name, classroom_id) VALUES (62, 'Student_62', 1)
  INTO student (id, name, classroom_id) VALUES (63, 'Student_63', 1)
  INTO student (id, name, classroom_id) VALUES (64, 'Student_64', 1)
  INTO student (id, name, classroom_id) VALUES (65, 'Student_65', 1)
  INTO student (id, name, classroom_id) VALUES (66, 'Student_66', 1)
  INTO student (id, name, classroom_id) VALUES (67, 'Student_67', 1)
  INTO student (id, name, classroom_id) VALUES (68, 'Student_68', 1)
  INTO student (id, name, classroom_id) VALUES (69, 'Student_69', 1)
  INTO student (id, name, classroom_id) VALUES (70, 'Student_70', 1)
  INTO student (id, name, classroom_id) VALUES (71, 'Student_71', 1)
  INTO student (id, name, classroom_id) VALUES (72, 'Student_72', 1)
  INTO student (id, name, classroom_id) VALUES (73, 'Student_73', 1)
  INTO student (id, name, classroom_id) VALUES (74, 'Student_74', 1)
  INTO student (id, name, classroom_id) VALUES (75, 'Student_75', 1)
  INTO student (id, name, classroom_id) VALUES (76, 'Student_76', 1)
  INTO student (id, name, classroom_id) VALUES (77, 'Student_77', 1)
  INTO student (id, name, classroom_id) VALUES (78, 'Student_78', 1)
  INTO student (id, name, classroom_id) VALUES (79, 'Student_79', 1)
  INTO student (id, name, classroom_id) VALUES (80, 'Student_80', 1)
  INTO student (id, name, classroom_id) VALUES (81, 'Student_81', 1)
  INTO student (id, name, classroom_id) VALUES (82, 'Student_82', 1)
  INTO student (id, name, classroom_id) VALUES (83, 'Student_83', 1)
  INTO student (id, name, classroom_id) VALUES (84, 'Student_84', 1)
  INTO student (id, name, classroom_id) VALUES (85, 'Student_85', 1)
  INTO student (id, name, classroom_id) VALUES (86, 'Student_86', 1)
  INTO student (id, name, classroom_id) VALUES (87, 'Student_87', 1)
  INTO student (id, name, classroom_id) VALUES (88, 'Student_88', 1)
  INTO student (id, name, classroom_id) VALUES (89, 'Student_89', 1)
  INTO student (id, name, classroom_id) VALUES (90, 'Student_90', 1)
  INTO student (id, name, classroom_id) VALUES (91, 'Student_91', 1)
  INTO student (id, name, classroom_id) VALUES (92, 'Student_92', 1)
  INTO student (id, name, classroom_id) VALUES (93, 'Student_93', 1)
  INTO student (id, name, classroom_id) VALUES (94, 'Student_94', 1)
  INTO student (id, name, classroom_id) VALUES (95, 'Student_95', 1)
  INTO student (id, name, classroom_id) VALUES (96, 'Student_96', 1)
  INTO student (id, name, classroom_id) VALUES (97, 'Student_97', 1)
  INTO student (id, name, classroom_id) VALUES (98, 'Student_98', 1)
  INTO student (id, name, classroom_id) VALUES (99, 'Student_99', 1)
  INTO student (id, name, classroom_id) VALUES (100, 'Student_100', 1)
SELECT * FROM DUAL;

-- STUDENTS: Records 501–600 (Oracle-compatible multi-row insert)
INSERT ALL
  INTO student (id, name, classroom_id) VALUES (400, 'Student_400', 5)
  INTO student (id, name, classroom_id) VALUES (401, 'Student_401', 5)
  INTO student (id, name, classroom_id) VALUES (402, 'Student_402', 5)
  INTO student (id, name, classroom_id) VALUES (403, 'Student_403', 5)
  INTO student (id, name, classroom_id) VALUES (404, 'Student_404', 5)
  INTO student (id, name, classroom_id) VALUES (405, 'Student_405', 5)
  INTO student (id, name, classroom_id) VALUES (406, 'Student_406', 5)
  INTO student (id, name, classroom_id) VALUES (407, 'Student_407', 5)
  INTO student (id, name, classroom_id) VALUES (408, 'Student_408', 5)
  INTO student (id, name, classroom_id) VALUES (409, 'Student_409', 5)
  INTO student (id, name, classroom_id) VALUES (410, 'Student_410', 5)
  INTO student (id, name, classroom_id) VALUES (411, 'Student_411', 5)
  INTO student (id, name, classroom_id) VALUES (412, 'Student_412', 5)
  INTO student (id, name, classroom_id) VALUES (413, 'Student_413', 5)
  INTO student (id, name, classroom_id) VALUES (414, 'Student_414', 5)
  INTO student (id, name, classroom_id) VALUES (415, 'Student_415', 5)
  INTO student (id, name, classroom_id) VALUES (416, 'Student_416', 5)
  INTO student (id, name, classroom_id) VALUES (417, 'Student_417', 5)
  INTO student (id, name, classroom_id) VALUES (418, 'Student_418', 5)
  INTO student (id, name, classroom_id) VALUES (419, 'Student_419', 5)
  INTO student (id, name, classroom_id) VALUES (420, 'Student_420', 5)
  INTO student (id, name, classroom_id) VALUES (421, 'Student_421', 5)
  INTO student (id, name, classroom_id) VALUES (422, 'Student_422', 5)
  INTO student (id, name, classroom_id) VALUES (423, 'Student_423', 5)
  INTO student (id, name, classroom_id) VALUES (424, 'Student_424', 5)
  INTO student (id, name, classroom_id) VALUES (425, 'Student_425', 5)
  INTO student (id, name, classroom_id) VALUES (426, 'Student_426', 5)
  INTO student (id, name, classroom_id) VALUES (427, 'Student_427', 5)
  INTO student (id, name, classroom_id) VALUES (428, 'Student_428', 5)
  INTO student (id, name, classroom_id) VALUES (429, 'Student_429', 5)
  INTO student (id, name, classroom_id) VALUES (430, 'Student_430', 5)
  INTO student (id, name, classroom_id) VALUES (431, 'Student_431', 5)
  INTO student (id, name, classroom_id) VALUES (432, 'Student_432', 5)
  INTO student (id, name, classroom_id) VALUES (433, 'Student_433', 5)
  INTO student (id, name, classroom_id) VALUES (434, 'Student_434', 5)
  INTO student (id, name, classroom_id) VALUES (435, 'Student_435', 5)
  INTO student (id, name, classroom_id) VALUES (436, 'Student_436', 5)
  INTO student (id, name, classroom_id) VALUES (437, 'Student_437', 5)
  INTO student (id, name, classroom_id) VALUES (438, 'Student_438', 5)
  INTO student (id, name, classroom_id) VALUES (439, 'Student_439', 5)
  INTO student (id, name, classroom_id) VALUES (440, 'Student_440', 5)
  INTO student (id, name, classroom_id) VALUES (441, 'Student_441', 5)
  INTO student (id, name, classroom_id) VALUES (442, 'Student_442', 5)
  INTO student (id, name, classroom_id) VALUES (443, 'Student_443', 5)
  INTO student (id, name, classroom_id) VALUES (444, 'Student_444', 5)
  INTO student (id, name, classroom_id) VALUES (445, 'Student_445', 5)
  INTO student (id, name, classroom_id) VALUES (446, 'Student_446', 5)
  INTO student (id, name, classroom_id) VALUES (447, 'Student_447', 5)
  INTO student (id, name, classroom_id) VALUES (448, 'Student_448', 5)
  INTO student (id, name, classroom_id) VALUES (449, 'Student_449', 5)
  INTO student (id, name, classroom_id) VALUES (450, 'Student_450', 5)
  INTO student (id, name, classroom_id) VALUES (451, 'Student_451', 5)
  INTO student (id, name, classroom_id) VALUES (452, 'Student_452', 5)
  INTO student (id, name, classroom_id) VALUES (453, 'Student_453', 5)
  INTO student (id, name, classroom_id) VALUES (454, 'Student_454', 5)
  INTO student (id, name, classroom_id) VALUES (455, 'Student_455', 5)
  INTO student (id, name, classroom_id) VALUES (456, 'Student_456', 5)
  INTO student (id, name, classroom_id) VALUES (457, 'Student_457', 5)
  INTO student (id, name, classroom_id) VALUES (458, 'Student_458', 5)
  INTO student (id, name, classroom_id) VALUES (459, 'Student_459', 5)
  INTO student (id, name, classroom_id) VALUES (460, 'Student_460', 5)
  INTO student (id, name, classroom_id) VALUES (461, 'Student_461', 5)
  INTO student (id, name, classroom_id) VALUES (462, 'Student_462', 5)
  INTO student (id, name, classroom_id) VALUES (463, 'Student_463', 5)
  INTO student (id, name, classroom_id) VALUES (464, 'Student_464', 5)
  INTO student (id, name, classroom_id) VALUES (465, 'Student_465', 5)
  INTO student (id, name, classroom_id) VALUES (466, 'Student_466', 5)
  INTO student (id, name, classroom_id) VALUES (467, 'Student_467', 5)
  INTO student (id, name, classroom_id) VALUES (468, 'Student_468', 5)
  INTO student (id, name, classroom_id) VALUES (469, 'Student_469', 5)
  INTO student (id, name, classroom_id) VALUES (470, 'Student_470', 5)
  INTO student (id, name, classroom_id) VALUES (471, 'Student_471', 5)
  INTO student (id, name, classroom_id) VALUES (472, 'Student_472', 5)
  INTO student (id, name, classroom_id) VALUES (473, 'Student_473', 5)
  INTO student (id, name, classroom_id) VALUES (474, 'Student_474', 5)
  INTO student (id, name, classroom_id) VALUES (475, 'Student_475', 5)
  INTO student (id, name, classroom_id) VALUES (476, 'Student_476', 5)
  INTO student (id, name, classroom_id) VALUES (477, 'Student_477', 5)
  INTO student (id, name, classroom_id) VALUES (478, 'Student_478', 5)
  INTO student (id, name, classroom_id) VALUES (479, 'Student_479', 5)
  INTO student (id, name, classroom_id) VALUES (480, 'Student_480', 5)
  INTO student (id, name, classroom_id) VALUES (481, 'Student_481', 5)
  INTO student (id, name, classroom_id) VALUES (482, 'Student_482', 5)
  INTO student (id, name, classroom_id) VALUES (483, 'Student_483', 5)
  INTO student (id, name, classroom_id) VALUES (484, 'Student_484', 5)
  INTO student (id, name, classroom_id) VALUES (485, 'Student_485', 5)
  INTO student (id, name, classroom_id) VALUES (486, 'Student_486', 5)
  INTO student (id, name, classroom_id) VALUES (487, 'Student_487', 5)
  INTO student (id, name, classroom_id) VALUES (488, 'Student_488', 5)
  INTO student (id, name, classroom_id) VALUES (489, 'Student_489', 5)
  INTO student (id, name, classroom_id) VALUES (490, 'Student_490', 5)
  INTO student (id, name, classroom_id) VALUES (491, 'Student_491', 5)
  INTO student (id, name, classroom_id) VALUES (492, 'Student_492', 5)
  INTO student (id, name, classroom_id) VALUES (493, 'Student_493', 5)
  INTO student (id, name, classroom_id) VALUES (494, 'Student_494', 5)
  INTO student (id, name, classroom_id) VALUES (495, 'Student_495', 5)
  INTO student (id, name, classroom_id) VALUES (496, 'Student_496', 5)
  INTO student (id, name, classroom_id) VALUES (497, 'Student_497', 5)
  INTO student (id, name, classroom_id) VALUES (498, 'Student_498', 5)
  INTO student (id, name, classroom_id) VALUES (499, 'Student_499', 5)
  INTO student (id, name, classroom_id) VALUES (500, 'Student_500', 5)
SELECT * FROM DUAL;

-- -- STUDENTS: First 100 records (Oracle-compatible multi-row insert)
INSERT ALL
  INTO student (id, name, classroom_id) VALUES (1, 'Student_1', 1)
  INTO student (id, name, classroom_id) VALUES (2, 'Student_2', 1)
  INTO student (id, name, classroom_id) VALUES (3, 'Student_3', 1)
  INTO student (id, name, classroom_id) VALUES (4, 'Student_4', 1)
  INTO student (id, name, classroom_id) VALUES (5, 'Student_5', 1)
  INTO student (id, name, classroom_id) VALUES (6, 'Student_6', 1)
  INTO student (id, name, classroom_id) VALUES (7, 'Student_7', 1)
  INTO student (id, name, classroom_id) VALUES (8, 'Student_8', 1)
  INTO student (id, name, classroom_id) VALUES (9, 'Student_9', 1)
  INTO student (id, name, classroom_id) VALUES (10, 'Student_10', 1)
  INTO student (id, name, classroom_id) VALUES (11, 'Student_11', 1)
  INTO student (id, name, classroom_id) VALUES (12, 'Student_12', 1)
  INTO student (id, name, classroom_id) VALUES (13, 'Student_13', 1)
  INTO student (id, name, classroom_id) VALUES (14, 'Student_14', 1)
  INTO student (id, name, classroom_id) VALUES (15, 'Student_15', 1)
  INTO student (id, name, classroom_id) VALUES (16, 'Student_16', 1)
  INTO student (id, name, classroom_id) VALUES (17, 'Student_17', 1)
  INTO student (id, name, classroom_id) VALUES (18, 'Student_18', 1)
  INTO student (id, name, classroom_id) VALUES (19, 'Student_19', 1)
  INTO student (id, name, classroom_id) VALUES (20, 'Student_20', 1)
  INTO student (id, name, classroom_id) VALUES (21, 'Student_21', 1)
  INTO student (id, name, classroom_id) VALUES (22, 'Student_22', 1)
  INTO student (id, name, classroom_id) VALUES (23, 'Student_23', 1)
  INTO student (id, name, classroom_id) VALUES (24, 'Student_24', 1)
  INTO student (id, name, classroom_id) VALUES (25, 'Student_25', 1)
  INTO student (id, name, classroom_id) VALUES (26, 'Student_26', 1)
  INTO student (id, name, classroom_id) VALUES (27, 'Student_27', 1)
  INTO student (id, name, classroom_id) VALUES (28, 'Student_28', 1)
  INTO student (id, name, classroom_id) VALUES (29, 'Student_29', 1)
  INTO student (id, name, classroom_id) VALUES (30, 'Student_30', 1)
  INTO student (id, name, classroom_id) VALUES (31, 'Student_31', 1)
  INTO student (id, name, classroom_id) VALUES (32, 'Student_32', 1)
  INTO student (id, name, classroom_id) VALUES (33, 'Student_33', 1)
  INTO student (id, name, classroom_id) VALUES (34, 'Student_34', 1)
  INTO student (id, name, classroom_id) VALUES (35, 'Student_35', 1)
  INTO student (id, name, classroom_id) VALUES (36, 'Student_36', 1)
  INTO student (id, name, classroom_id) VALUES (37, 'Student_37', 1)
  INTO student (id, name, classroom_id) VALUES (38, 'Student_38', 1)
  INTO student (id, name, classroom_id) VALUES (39, 'Student_39', 1)
  INTO student (id, name, classroom_id) VALUES (40, 'Student_40', 1)
  INTO student (id, name, classroom_id) VALUES (41, 'Student_41', 1)
  INTO student (id, name, classroom_id) VALUES (42, 'Student_42', 1)
  INTO student (id, name, classroom_id) VALUES (43, 'Student_43', 1)
  INTO student (id, name, classroom_id) VALUES (44, 'Student_44', 1)
  INTO student (id, name, classroom_id) VALUES (45, 'Student_45', 1)
  INTO student (id, name, classroom_id) VALUES (46, 'Student_46', 1)
  INTO student (id, name, classroom_id) VALUES (47, 'Student_47', 1)
  INTO student (id, name, classroom_id) VALUES (48, 'Student_48', 1)
  INTO student (id, name, classroom_id) VALUES (49, 'Student_49', 1)
  INTO student (id, name, classroom_id) VALUES (50, 'Student_50', 1)
  INTO student (id, name, classroom_id) VALUES (51, 'Student_51', 1)
  INTO student (id, name, classroom_id) VALUES (52, 'Student_52', 1)
  INTO student (id, name, classroom_id) VALUES (53, 'Student_53', 1)
  INTO student (id, name, classroom_id) VALUES (54, 'Student_54', 1)
  INTO student (id, name, classroom_id) VALUES (55, 'Student_55', 1)
  INTO student (id, name, classroom_id) VALUES (56, 'Student_56', 1)
  INTO student (id, name, classroom_id) VALUES (57, 'Student_57', 1)
  INTO student (id, name, classroom_id) VALUES (58, 'Student_58', 1)
  INTO student (id, name, classroom_id) VALUES (59, 'Student_59', 1)
  INTO student (id, name, classroom_id) VALUES (60, 'Student_60', 1)
  INTO student (id, name, classroom_id) VALUES (61, 'Student_61', 1)
  INTO student (id, name, classroom_id) VALUES (62, 'Student_62', 1)
  INTO student (id, name, classroom_id) VALUES (63, 'Student_63', 1)
  INTO student (id, name, classroom_id) VALUES (64, 'Student_64', 1)
  INTO student (id, name, classroom_id) VALUES (65, 'Student_65', 1)
  INTO student (id, name, classroom_id) VALUES (66, 'Student_66', 1)
  INTO student (id, name, classroom_id) VALUES (67, 'Student_67', 1)
  INTO student (id, name, classroom_id) VALUES (68, 'Student_68', 1)
  INTO student (id, name, classroom_id) VALUES (69, 'Student_69', 1)
  INTO student (id, name, classroom_id) VALUES (70, 'Student_70', 1)
  INTO student (id, name, classroom_id) VALUES (71, 'Student_71', 1)
  INTO student (id, name, classroom_id) VALUES (72, 'Student_72', 1)
  INTO student (id, name, classroom_id) VALUES (73, 'Student_73', 1)
  INTO student (id, name, classroom_id) VALUES (74, 'Student_74', 1)
  INTO student (id, name, classroom_id) VALUES (75, 'Student_75', 1)
  INTO student (id, name, classroom_id) VALUES (76, 'Student_76', 1)
  INTO student (id, name, classroom_id) VALUES (77, 'Student_77', 1)
  INTO student (id, name, classroom_id) VALUES (78, 'Student_78', 1)
  INTO student (id, name, classroom_id) VALUES (79, 'Student_79', 1)
  INTO student (id, name, classroom_id) VALUES (80, 'Student_80', 1)
  INTO student (id, name, classroom_id) VALUES (81, 'Student_81', 1)
  INTO student (id, name, classroom_id) VALUES (82, 'Student_82', 1)
  INTO student (id, name, classroom_id) VALUES (83, 'Student_83', 1)
  INTO student (id, name, classroom_id) VALUES (84, 'Student_84', 1)
  INTO student (id, name, classroom_id) VALUES (85, 'Student_85', 1)
  INTO student (id, name, classroom_id) VALUES (86, 'Student_86', 1)
  INTO student (id, name, classroom_id) VALUES (87, 'Student_87', 1)
  INTO student (id, name, classroom_id) VALUES (88, 'Student_88', 1)
  INTO student (id, name, classroom_id) VALUES (89, 'Student_89', 1)
  INTO student (id, name, classroom_id) VALUES (90, 'Student_90', 1)
  INTO student (id, name, classroom_id) VALUES (91, 'Student_91', 1)
  INTO student (id, name, classroom_id) VALUES (92, 'Student_92', 1)
  INTO student (id, name, classroom_id) VALUES (93, 'Student_93', 1)
  INTO student (id, name, classroom_id) VALUES (94, 'Student_94', 1)
  INTO student (id, name, classroom_id) VALUES (95, 'Student_95', 1)
  INTO student (id, name, classroom_id) VALUES (96, 'Student_96', 1)
  INTO student (id, name, classroom_id) VALUES (97, 'Student_97', 1)
  INTO student (id, name, classroom_id) VALUES (98, 'Student_98', 1)
  INTO student (id, name, classroom_id) VALUES (99, 'Student_99', 1)
  INTO student (id, name, classroom_id) VALUES (100, 'Student_100', 1)
SELECT * FROM DUAL;

-- STUDENTS: Records 501–600 (Oracle-compatible multi-row insert)
INSERT ALL
  INTO student (id, name, classroom_id) VALUES (400, 'Student_400', 5)
  INTO student (id, name, classroom_id) VALUES (401, 'Student_401', 5)
  INTO student (id, name, classroom_id) VALUES (402, 'Student_402', 5)
  INTO student (id, name, classroom_id) VALUES (403, 'Student_403', 5)
  INTO student (id, name, classroom_id) VALUES (404, 'Student_404', 5)
  INTO student (id, name, classroom_id) VALUES (405, 'Student_405', 5)
  INTO student (id, name, classroom_id) VALUES (406, 'Student_406', 5)
  INTO student (id, name, classroom_id) VALUES (407, 'Student_407', 5)
  INTO student (id, name, classroom_id) VALUES (408, 'Student_408', 5)
  INTO student (id, name, classroom_id) VALUES (409, 'Student_409', 5)
  INTO student (id, name, classroom_id) VALUES (410, 'Student_410', 5)
  INTO student (id, name, classroom_id) VALUES (411, 'Student_411', 5)
  INTO student (id, name, classroom_id) VALUES (412, 'Student_412', 5)
  INTO student (id, name, classroom_id) VALUES (413, 'Student_413', 5)
  INTO student (id, name, classroom_id) VALUES (414, 'Student_414', 5)
  INTO student (id, name, classroom_id) VALUES (415, 'Student_415', 5)
  INTO student (id, name, classroom_id) VALUES (416, 'Student_416', 5)
  INTO student (id, name, classroom_id) VALUES (417, 'Student_417', 5)
  INTO student (id, name, classroom_id) VALUES (418, 'Student_418', 5)
  INTO student (id, name, classroom_id) VALUES (419, 'Student_419', 5)
  INTO student (id, name, classroom_id) VALUES (420, 'Student_420', 5)
  INTO student (id, name, classroom_id) VALUES (421, 'Student_421', 5)
  INTO student (id, name, classroom_id) VALUES (422, 'Student_422', 5)
  INTO student (id, name, classroom_id) VALUES (423, 'Student_423', 5)
  INTO student (id, name, classroom_id) VALUES (424, 'Student_424', 5)
  INTO student (id, name, classroom_id) VALUES (425, 'Student_425', 5)
  INTO student (id, name, classroom_id) VALUES (426, 'Student_426', 5)
  INTO student (id, name, classroom_id) VALUES (427, 'Student_427', 5)
  INTO student (id, name, classroom_id) VALUES (428, 'Student_428', 5)
  INTO student (id, name, classroom_id) VALUES (429, 'Student_429', 5)
  INTO student (id, name, classroom_id) VALUES (430, 'Student_430', 5)
  INTO student (id, name, classroom_id) VALUES (431, 'Student_431', 5)
  INTO student (id, name, classroom_id) VALUES (432, 'Student_432', 5)
  INTO student (id, name, classroom_id) VALUES (433, 'Student_433', 5)
  INTO student (id, name, classroom_id) VALUES (434, 'Student_434', 5)
  INTO student (id, name, classroom_id) VALUES (435, 'Student_435', 5)
  INTO student (id, name, classroom_id) VALUES (436, 'Student_436', 5)
  INTO student (id, name, classroom_id) VALUES (437, 'Student_437', 5)
  INTO student (id, name, classroom_id) VALUES (438, 'Student_438', 5)
  INTO student (id, name, classroom_id) VALUES (439, 'Student_439', 5)
  INTO student (id, name, classroom_id) VALUES (440, 'Student_440', 5)
  INTO student (id, name, classroom_id) VALUES (441, 'Student_441', 5)
  INTO student (id, name, classroom_id) VALUES (442, 'Student_442', 5)
  INTO student (id, name, classroom_id) VALUES (443, 'Student_443', 5)
  INTO student (id, name, classroom_id) VALUES (444, 'Student_444', 5)
  INTO student (id, name, classroom_id) VALUES (445, 'Student_445', 5)
  INTO student (id, name, classroom_id) VALUES (446, 'Student_446', 5)
  INTO student (id, name, classroom_id) VALUES (447, 'Student_447', 5)
  INTO student (id, name, classroom_id) VALUES (448, 'Student_448', 5)
  INTO student (id, name, classroom_id) VALUES (449, 'Student_449', 5)
  INTO student (id, name, classroom_id) VALUES (450, 'Student_450', 5)
  INTO student (id, name, classroom_id) VALUES (451, 'Student_451', 5)
  INTO student (id, name, classroom_id) VALUES (452, 'Student_452', 5)
  INTO student (id, name, classroom_id) VALUES (453, 'Student_453', 5)
  INTO student (id, name, classroom_id) VALUES (454, 'Student_454', 5)
  INTO student (id, name, classroom_id) VALUES (455, 'Student_455', 5)
  INTO student (id, name, classroom_id) VALUES (456, 'Student_456', 5)
  INTO student (id, name, classroom_id) VALUES (457, 'Student_457', 5)
  INTO student (id, name, classroom_id) VALUES (458, 'Student_458', 5)
  INTO student (id, name, classroom_id) VALUES (459, 'Student_459', 5)
  INTO student (id, name, classroom_id) VALUES (460, 'Student_460', 5)
  INTO student (id, name, classroom_id) VALUES (461, 'Student_461', 5)
  INTO student (id, name, classroom_id) VALUES (462, 'Student_462', 5)
  INTO student (id, name, classroom_id) VALUES (463, 'Student_463', 5)
  INTO student (id, name, classroom_id) VALUES (464, 'Student_464', 5)
  INTO student (id, name, classroom_id) VALUES (465, 'Student_465', 5)
  INTO student (id, name, classroom_id) VALUES (466, 'Student_466', 5)
  INTO student (id, name, classroom_id) VALUES (467, 'Student_467', 5)
  INTO student (id, name, classroom_id) VALUES (468, 'Student_468', 5)
  INTO student (id, name, classroom_id) VALUES (469, 'Student_469', 5)
  INTO student (id, name, classroom_id) VALUES (470, 'Student_470', 5)
  INTO student (id, name, classroom_id) VALUES (471, 'Student_471', 5)
  INTO student (id, name, classroom_id) VALUES (472, 'Student_472', 5)
  INTO student (id, name, classroom_id) VALUES (473, 'Student_473', 5)
  INTO student (id, name, classroom_id) VALUES (474, 'Student_474', 5)
  INTO student (id, name, classroom_id) VALUES (475, 'Student_475', 5)
  INTO student (id, name, classroom_id) VALUES (476, 'Student_476', 5)
  INTO student (id, name, classroom_id) VALUES (477, 'Student_477', 5)
  INTO student (id, name, classroom_id) VALUES (478, 'Student_478', 5)
  INTO student (id, name, classroom_id) VALUES (479, 'Student_479', 5)
  INTO student (id, name, classroom_id) VALUES (480, 'Student_480', 5)
  INTO student (id, name, classroom_id) VALUES (481, 'Student_481', 5)
  INTO student (id, name, classroom_id) VALUES (482, 'Student_482', 5)
  INTO student (id, name, classroom_id) VALUES (483, 'Student_483', 5)
  INTO student (id, name, classroom_id) VALUES (484, 'Student_484', 5)
  INTO student (id, name, classroom_id) VALUES (485, 'Student_485', 5)
  INTO student (id, name, classroom_id) VALUES (486, 'Student_486', 5)
  INTO student (id, name, classroom_id) VALUES (487, 'Student_487', 5)
  INTO student (id, name, classroom_id) VALUES (488, 'Student_488', 5)
  INTO student (id, name, classroom_id) VALUES (489, 'Student_489', 5)
  INTO student (id, name, classroom_id) VALUES (490, 'Student_490', 5)
  INTO student (id, name, classroom_id) VALUES (491, 'Student_491', 5)
  INTO student (id, name, classroom_id) VALUES (492, 'Student_492', 5)
  INTO student (id, name, classroom_id) VALUES (493, 'Student_493', 5)
  INTO student (id, name, classroom_id) VALUES (494, 'Student_494', 5)
  INTO student (id, name, classroom_id) VALUES (495, 'Student_495', 5)
  INTO student (id, name, classroom_id) VALUES (496, 'Student_496', 5)
  INTO student (id, name, classroom_id) VALUES (497, 'Student_497', 5)
  INTO student (id, name, classroom_id) VALUES (498, 'Student_498', 5)
  INTO student (id, name, classroom_id) VALUES (499, 'Student_499', 5)
  INTO student (id, name, classroom_id) VALUES (500, 'Student_500', 5)
SELECT * FROM DUAL;

-- ENROLLMENTS: Class 1 (Oracle-compatible multi-row insert, students 1–10, all 6 subjects, random teachers)
INSERT ALL
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (1, 1, 1, 1, 2, 87)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (2, 1, 2, 1, 5, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (3, 1, 3, 1, 1, 65)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (4, 1, 4, 1, 4, 92)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (5, 1, 5, 1, 3, 56)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (6, 1, 6, 1, 6, 78)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (7, 2, 1, 1, 4, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (8, 2, 2, 1, 2, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (9, 2, 3, 1, 5, 67)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (10, 2, 4, 1, 1, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (11, 2, 5, 1, 6, 53)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (12, 2, 6, 1, 3, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (13, 3, 1, 1, 5, 84)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (14, 3, 2, 1, 1, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (15, 3, 3, 1, 2, 62)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (16, 3, 4, 1, 6, 91)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (17, 3, 5, 1, 4, 60)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (18, 3, 6, 1, 3, 80)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (19, 4, 1, 1, 3, 93)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (20, 4, 2, 1, 2, 70)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (21, 4, 3, 1, 6, 66)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (22, 4, 4, 1, 5, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (23, 4, 5, 1, 1, 55)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (24, 4, 6, 1, 4, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (25, 5, 1, 1, 2, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (26, 5, 2, 1, 3, 73)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (27, 5, 3, 1, 4, 69)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (28, 5, 4, 1, 5, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (29, 5, 5, 1, 6, 61)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (30, 5, 6, 1, 1, 82)
SELECT * FROM DUAL;

-- ENROLLMENTS: Class 2, students 101–200, each assigned a course and teacher (Oracle-compatible multi-row insert)
INSERT ALL
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (101, 101, 1, 2, 1, 84)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (102, 102, 2, 2, 2, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (103, 103, 3, 2, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (104, 104, 4, 2, 4, 72)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (105, 105, 5, 2, 5, 75)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (106, 106, 6, 2, 6, 89)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (107, 107, 1, 2, 1, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (108, 108, 2, 2, 2, 78)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (109, 109, 3, 2, 3, 91)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (110, 110, 4, 2, 4, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (111, 111, 5, 2, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (112, 112, 6, 2, 6, 84)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (113, 113, 1, 2, 1, 80)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (114, 114, 2, 2, 2, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (115, 115, 3, 2, 3, 92)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (116, 116, 4, 2, 4, 75)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (117, 117, 5, 2, 5, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (118, 118, 6, 2, 6, 86)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (119, 119, 1, 2, 1, 83)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (120, 120, 2, 2, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (121, 121, 3, 2, 3, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (122, 122, 4, 2, 4, 72)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (123, 123, 5, 2, 5, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (124, 124, 6, 2, 6, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (125, 125, 1, 2, 1, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (126, 126, 2, 2, 2, 78)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (127, 127, 3, 2, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (128, 128, 4, 2, 4, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (129, 129, 5, 2, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (130, 130, 6, 2, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (131, 131, 1, 2, 1, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (132, 132, 2, 2, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (133, 133, 3, 2, 3, 91)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (134, 134, 4, 2, 4, 67)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (135, 135, 5, 2, 5, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (136, 136, 6, 2, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (137, 137, 1, 2, 1, 82)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (138, 138, 2, 2, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (139, 139, 3, 2, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (140, 140, 4, 2, 4, 73)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (141, 141, 5, 2, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (142, 142, 6, 2, 6, 84)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (143, 143, 1, 2, 1, 80)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (144, 144, 2, 2, 2, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (145, 145, 3, 2, 3, 92)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (146, 146, 4, 2, 4, 75)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (147, 147, 5, 2, 5, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (148, 148, 6, 2, 6, 86)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (149, 149, 1, 2, 1, 83)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (150, 150, 2, 2, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (151, 151, 3, 2, 3, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (152, 152, 4, 2, 4, 72)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (153, 153, 5, 2, 5, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (154, 154, 6, 2, 6, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (155, 155, 1, 2, 1, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (156, 156, 2, 2, 2, 78)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (157, 157, 3, 2, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (158, 158, 4, 2, 4, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (159, 159, 5, 2, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (160, 160, 6, 2, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (161, 161, 1, 2, 1, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (162, 162, 2, 2, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (163, 163, 3, 2, 3, 91)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (164, 164, 4, 2, 4, 67)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (165, 165, 5, 2, 5, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (166, 166, 6, 2, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (167, 167, 1, 2, 1, 82)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (168, 168, 2, 2, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (169, 169, 3, 2, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (170, 170, 4, 2, 4, 73)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (171, 171, 5, 2, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (172, 172, 6, 2, 6, 84)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (173, 173, 1, 2, 1, 80)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (174, 174, 2, 2, 2, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (175, 175, 3, 2, 3, 92)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (176, 176, 4, 2, 4, 75)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (177, 177, 5, 2, 5, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (178, 178, 6, 2, 6, 86)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (179, 179, 1, 2, 1, 83)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (180, 180, 2, 2, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (181, 181, 3, 2, 3, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (182, 182, 4, 2, 4, 72)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (183, 183, 5, 2, 5, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (184, 184, 6, 2, 6, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (185, 185, 1, 2, 1, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (186, 186, 2, 2, 2, 78)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (187, 187, 3, 2, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (188, 188, 4, 2, 4, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (189, 189, 5, 2, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (190, 190, 6, 2, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (191, 191, 1, 2, 1, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (192, 192, 2, 2, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (193, 193, 3, 2, 3, 91)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (194, 194, 4, 2, 4, 67)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (195, 195, 5, 2, 5, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (196, 196, 6, 2, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (197, 197, 1, 2, 1, 82)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (198, 198, 2, 2, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (199, 199, 3, 2, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (200, 200, 4, 2, 4, 76)
SELECT * FROM DUAL;

-- -- CLASSES (Oracle-compatible multi-row insert)
-- INSERT ALL
--   INTO classroom (id, name) VALUES (1, 'Class 1')
--   INTO classroom (id, name) VALUES (2, 'Class 2')
--   INTO classroom (id, name) VALUES (3, 'Class 3')
--   INTO classroom (id, name) VALUES (4, 'Class 4')
--   INTO classroom (id, name) VALUES (5, 'Class 5')
--   INTO classroom (id, name) VALUES (6, 'Class 6')
--   INTO classroom (id, name) VALUES (7, 'Class 7')
--   INTO classroom (id, name) VALUES (8, 'Class 8')
--   INTO classroom (id, name) VALUES (9, 'Class 9')
--   INTO classroom (id, name) VALUES (10, 'Class 10')
-- SELECT * FROM DUAL;

-- --SUBJECTS/COURSES (Oracle-compatible multi-row insert)
-- INSERT ALL
--   INTO course (id, title) VALUES (1, 'English')
--   INTO course (id, title) VALUES (2, 'Hindi')
--   INTO course (id, title) VALUES (3, 'Telugu')
--   INTO course (id, title) VALUES (4, 'Social')
--   INTO course (id, title) VALUES (5, 'Science')
--   INTO course (id, title) VALUES (6, 'Maths')
-- SELECT * FROM DUAL;

-- -- TEACHERS (Oracle-compatible multi-row insert, 60 records)
-- INSERT ALL
--   INTO teacher (id, name) VALUES (1, 'Alice Johnson')
--   INTO teacher (id, name) VALUES (2, 'Bob Smith')
--   INTO teacher (id, name) VALUES (3, 'Carol Lee')
--   INTO teacher (id, name) VALUES (4, 'David Kim')
--   INTO teacher (id, name) VALUES (5, 'Eva Brown')
--   INTO teacher (id, name) VALUES (6, 'Frank White')
--   INTO teacher (id, name) VALUES (7, 'Grace Green')
--   INTO teacher (id, name) VALUES (8, 'Henry Black')
--   INTO teacher (id, name) VALUES (9, 'Ivy Young')
--   INTO teacher (id, name) VALUES (10, 'Jack King')
--   INTO teacher (id, name) VALUES (11, 'Kathy Hall')
--   INTO teacher (id, name) VALUES (12, 'Leo Scott')
--   INTO teacher (id, name) VALUES (13, 'Mona Adams')
--   INTO teacher (id, name) VALUES (14, 'Nina Clark')
--   INTO teacher (id, name) VALUES (15, 'Oscar Lewis')
--   INTO teacher (id, name) VALUES (16, 'Paul Walker')
--   INTO teacher (id, name) VALUES (17, 'Quinn Allen')
--   INTO teacher (id, name) VALUES (18, 'Rita Baker')
--   INTO teacher (id, name) VALUES (19, 'Sam Carter')
--   INTO teacher (id, name) VALUES (20, 'Tina Davis')
--   INTO teacher (id, name) VALUES (21, 'Uma Evans')
--   INTO teacher (id, name) VALUES (22, 'Vera Foster')
--   INTO teacher (id, name) VALUES (23, 'Will Harris')
--   INTO teacher (id, name) VALUES (24, 'Xena James')
--   INTO teacher (id, name) VALUES (25, 'Yuri Kelly')
--   INTO teacher (id, name) VALUES (26, 'Zane Lopez')
--   INTO teacher (id, name) VALUES (27, 'Amy Moore')
--   INTO teacher (id, name) VALUES (28, 'Ben Nelson')
--   INTO teacher (id, name) VALUES (29, 'Cody Ortiz')
--   INTO teacher (id, name) VALUES (30, 'Dina Perez')
--   INTO teacher (id, name) VALUES (31, 'Eli Reed')
--   INTO teacher (id, name) VALUES (32, 'Fay Shaw')
--   INTO teacher (id, name) VALUES (33, 'Gus Turner')
--   INTO teacher (id, name) VALUES (34, 'Hope Underwood')
--   INTO teacher (id, name) VALUES (35, 'Ian Vincent')
--   INTO teacher (id, name) VALUES (36, 'Jill Ward')
--   INTO teacher (id, name) VALUES (37, 'Kyle Xu')
--   INTO teacher (id, name) VALUES (38, 'Lara Young')
--   INTO teacher (id, name) VALUES (39, 'Mick Zane')
--   INTO teacher (id, name) VALUES (40, 'Nora Abbott')
--   INTO teacher (id, name) VALUES (41, 'Omar Brooks')
--   INTO teacher (id, name) VALUES (42, 'Pia Cruz')
--   INTO teacher (id, name) VALUES (43, 'Qing Du')
--   INTO teacher (id, name) VALUES (44, 'Rex Fox')
--   INTO teacher (id, name) VALUES (45, 'Sia Grant')
--   INTO teacher (id, name) VALUES (46, 'Tom Hill')
--   INTO teacher (id, name) VALUES (47, 'Usha Iyer')
--   INTO teacher (id, name) VALUES (48, 'Vic Jones')
--   INTO teacher (id, name) VALUES (49, 'Walt Kim')
--   INTO teacher (id, name) VALUES (50, 'Yana Lin')
--   INTO teacher (id, name) VALUES (51, 'Zara Patel')
--   INTO teacher (id, name) VALUES (52, 'Rohan Mehta')
--   INTO teacher (id, name) VALUES (53, 'Priya Singh')
--   INTO teacher (id, name) VALUES (54, 'Anil Kumar')
--   INTO teacher (id, name) VALUES (55, 'Meena Rao')
--   INTO teacher (id, name) VALUES (56, 'Deepak Shah')
--   INTO teacher (id, name) VALUES (57, 'Sonal Jain')
--   INTO teacher (id, name) VALUES (58, 'Vikas Gupta')
--   INTO teacher (id, name) VALUES (59, 'Ritu Verma')
--   INTO teacher (id, name) VALUES (60, 'Amit Sinha')
-- SELECT * FROM DUAL;

-- -- STUDENTS: Class 1 (Oracle-compatible multi-row insert)
INSERT ALL
  INTO student (id, name, classroom_id) VALUES (300, 'Student_300', 4)
  INTO student (id, name, classroom_id) VALUES (301, 'Student_301', 4)
  INTO student (id, name, classroom_id) VALUES (302, 'Student_302', 4)
  INTO student (id, name, classroom_id) VALUES (303, 'Student_303', 4)
  INTO student (id, name, classroom_id) VALUES (304, 'Student_304', 4)
  INTO student (id, name, classroom_id) VALUES (305, 'Student_305', 4)
  INTO student (id, name, classroom_id) VALUES (306, 'Student_306', 4)
  INTO student (id, name, classroom_id) VALUES (307, 'Student_307', 4)
  INTO student (id, name, classroom_id) VALUES (308, 'Student_308', 4)
  INTO student (id, name, classroom_id) VALUES (309, 'Student_309', 4)
  INTO student (id, name, classroom_id) VALUES (310, 'Student_310', 4)
  INTO student (id, name, classroom_id) VALUES (311, 'Student_311', 4)
  INTO student (id, name, classroom_id) VALUES (312, 'Student_312', 4)
  INTO student (id, name, classroom_id) VALUES (313, 'Student_313', 4)
  INTO student (id, name, classroom_id) VALUES (314, 'Student_314', 4)
  INTO student (id, name, classroom_id) VALUES (315, 'Student_315', 4)
  INTO student (id, name, classroom_id) VALUES (316, 'Student_316', 4)
  INTO student (id, name, classroom_id) VALUES (317, 'Student_317', 4)
  INTO student (id, name, classroom_id) VALUES (318, 'Student_318', 4)
  INTO student (id, name, classroom_id) VALUES (319, 'Student_319', 4)
  INTO student (id, name, classroom_id) VALUES (320, 'Student_320', 4)
  INTO student (id, name, classroom_id) VALUES (321, 'Student_321', 4)
  INTO student (id, name, classroom_id) VALUES (322, 'Student_322', 4)
  INTO student (id, name, classroom_id) VALUES (323, 'Student_323', 4)
  INTO student (id, name, classroom_id) VALUES (324, 'Student_324', 4)
  INTO student (id, name, classroom_id) VALUES (325, 'Student_325', 4)
  INTO student (id, name, classroom_id) VALUES (326, 'Student_326', 4)
  INTO student (id, name, classroom_id) VALUES (327, 'Student_327', 4)
  INTO student (id, name, classroom_id) VALUES (328, 'Student_328', 4)
  INTO student (id, name, classroom_id) VALUES (329, 'Student_329', 4)
  INTO student (id, name, classroom_id) VALUES (330, 'Student_330', 4)
  INTO student (id, name, classroom_id) VALUES (331, 'Student_331', 4)
  INTO student (id, name, classroom_id) VALUES (332, 'Student_332', 4)
  INTO student (id, name, classroom_id) VALUES (333, 'Student_333', 4)
  INTO student (id, name, classroom_id) VALUES (334, 'Student_334', 4)
  INTO student (id, name, classroom_id) VALUES (335, 'Student_335', 4)
  INTO student (id, name, classroom_id) VALUES (336, 'Student_336', 4)
  INTO student (id, name, classroom_id) VALUES (337, 'Student_337', 4)
  INTO student (id, name, classroom_id) VALUES (338, 'Student_338', 4)
  INTO student (id, name, classroom_id) VALUES (339, 'Student_339', 4)
  INTO student (id, name, classroom_id) VALUES (340, 'Student_340', 4)
  INTO student (id, name, classroom_id) VALUES (341, 'Student_341', 4)
  INTO student (id, name, classroom_id) VALUES (342, 'Student_342', 4)
  INTO student (id, name, classroom_id) VALUES (343, 'Student_343', 4)
  INTO student (id, name, classroom_id) VALUES (344, 'Student_344', 4)
  INTO student (id, name, classroom_id) VALUES (345, 'Student_345', 4)
  INTO student (id, name, classroom_id) VALUES (346, 'Student_346', 4)
  INTO student (id, name, classroom_id) VALUES (347, 'Student_347', 4)
  INTO student (id, name, classroom_id) VALUES (348, 'Student_348', 4)
  INTO student (id, name, classroom_id) VALUES (349, 'Student_349', 4)
  INTO student (id, name, classroom_id) VALUES (350, 'Student_350', 4)
  INTO student (id, name, classroom_id) VALUES (351, 'Student_351', 4)
  INTO student (id, name, classroom_id) VALUES (352, 'Student_352', 4)
  INTO student (id, name, classroom_id) VALUES (353, 'Student_353', 4)
  INTO student (id, name, classroom_id) VALUES (354, 'Student_354', 4)
  INTO student (id, name, classroom_id) VALUES (355, 'Student_355', 4)
  INTO student (id, name, classroom_id) VALUES (356, 'Student_356', 4)
  INTO student (id, name, classroom_id) VALUES (357, 'Student_357', 4)
  INTO student (id, name, classroom_id) VALUES (358, 'Student_358', 4)
  INTO student (id, name, classroom_id) VALUES (359, 'Student_359', 4)
  INTO student (id, name, classroom_id) VALUES (360, 'Student_360', 4)
  INTO student (id, name, classroom_id) VALUES (361, 'Student_361', 4)
  INTO student (id, name, classroom_id) VALUES (362, 'Student_362', 4)
  INTO student (id, name, classroom_id) VALUES (363, 'Student_363', 4)
  INTO student (id, name, classroom_id) VALUES (364, 'Student_364', 4)
  INTO student (id, name, classroom_id) VALUES (365, 'Student_365', 4)
  INTO student (id, name, classroom_id) VALUES (366, 'Student_366', 4)
  INTO student (id, name, classroom_id) VALUES (367, 'Student_367', 4)
  INTO student (id, name, classroom_id) VALUES (368, 'Student_368', 4)
  INTO student (id, name, classroom_id) VALUES (369, 'Student_369', 4)
  INTO student (id, name, classroom_id) VALUES (370, 'Student_370', 4)
  INTO student (id, name, classroom_id) VALUES (371, 'Student_371', 4)
  INTO student (id, name, classroom_id) VALUES (372, 'Student_372', 4)
  INTO student (id, name, classroom_id) VALUES (373, 'Student_373', 4)
  INTO student (id, name, classroom_id) VALUES (374, 'Student_374', 4)
  INTO student (id, name, classroom_id) VALUES (375, 'Student_375', 4)
  INTO student (id, name, classroom_id) VALUES (376, 'Student_376', 4)
  INTO student (id, name, classroom_id) VALUES (377, 'Student_377', 4)
  INTO student (id, name, classroom_id) VALUES (378, 'Student_378', 4)
  INTO student (id, name, classroom_id) VALUES (379, 'Student_379', 4)
  INTO student (id, name, classroom_id) VALUES (380, 'Student_380', 4)
  INTO student (id, name, classroom_id) VALUES (381, 'Student_381', 4)
  INTO student (id, name, classroom_id) VALUES (382, 'Student_382', 4)
  INTO student (id, name, classroom_id) VALUES (383, 'Student_383', 4)
  INTO student (id, name, classroom_id) VALUES (384, 'Student_384', 4)
  INTO student (id, name, classroom_id) VALUES (385, 'Student_385', 4)
  INTO student (id, name, classroom_id) VALUES (386, 'Student_386', 4)
  INTO student (id, name, classroom_id) VALUES (387, 'Student_387', 4)
  INTO student (id, name, classroom_id) VALUES (388, 'Student_388', 4)
  INTO student (id, name, classroom_id) VALUES (389, 'Student_389', 4)
  INTO student (id, name, classroom_id) VALUES (390, 'Student_390', 4)
  INTO student (id, name, classroom_id) VALUES (391, 'Student_391', 4)
  INTO student (id, name, classroom_id) VALUES (392, 'Student_392', 4)
  INTO student (id, name, classroom_id) VALUES (393, 'Student_393', 4)
  INTO student (id, name, classroom_id) VALUES (394, 'Student_394', 4)
  INTO student (id, name, classroom_id) VALUES (395, 'Student_395', 4)
  INTO student (id, name, classroom_id) VALUES (396, 'Student_396', 4)
  INTO student (id, name, classroom_id) VALUES (397, 'Student_397', 4)
  INTO student (id, name, classroom_id) VALUES (398, 'Student_398', 4)
  INTO student (id, name, classroom_id) VALUES (399, 'Student_399', 4)
  INTO student (id, name, classroom_id) VALUES (400, 'Student_400', 4)
SELECT * FROM DUAL;

-- ENROLLMENTS: Class 1, students 1–100, each assigned a course and teacher (Oracle-compatible multi-row insert)
INSERT ALL
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (1, 1, 1, 1, 1, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (2, 2, 2, 1, 2, 78)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (3, 3, 3, 1, 3, 91)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (4, 4, 4, 1, 4, 67)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (5, 5, 5, 1, 5, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (6, 6, 6, 1, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (7, 7, 1, 1, 1, 82)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (8, 8, 2, 1, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (9, 9, 3, 1, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (10, 10, 4, 1, 4, 73)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (11, 11, 5, 1, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (12, 12, 6, 1, 6, 84)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (13, 13, 1, 1, 1, 80)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (14, 14, 2, 1, 2, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (15, 15, 3, 1, 3, 92)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (16, 16, 4, 1, 4, 75)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (17, 17, 5, 1, 5, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (18, 18, 6, 1, 6, 86)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (19, 19, 1, 1, 1, 83)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (20, 20, 2, 1, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (21, 21, 3, 1, 3, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (22, 22, 4, 1, 4, 72)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (23, 23, 5, 1, 5, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (24, 24, 6, 1, 6, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (25, 25, 1, 1, 1, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (26, 26, 2, 1, 2, 78)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (27, 27, 3, 1, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (28, 28, 4, 1, 4, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (29, 29, 5, 1, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (30, 30, 6, 1, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (31, 31, 1, 1, 1, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (32, 32, 2, 1, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (33, 33, 3, 1, 3, 91)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (34, 34, 4, 1, 4, 67)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (35, 35, 5, 1, 5, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (36, 36, 6, 1, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (37, 37, 1, 1, 1, 82)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (38, 38, 2, 1, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (39, 39, 3, 1, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (40, 40, 4, 1, 4, 73)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (41, 41, 5, 1, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (42, 42, 6, 1, 6, 84)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (43, 43, 1, 1, 1, 80)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (44, 44, 2, 1, 2, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (45, 45, 3, 1, 3, 92)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (46, 46, 4, 1, 4, 75)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (47, 47, 5, 1, 5, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (48, 48, 6, 1, 6, 86)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (49, 49, 1, 1, 1, 83)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (50, 50, 2, 1, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (51, 51, 3, 1, 3, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (52, 52, 4, 1, 4, 72)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (53, 53, 5, 1, 5, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (54, 54, 6, 1, 6, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (55, 55, 1, 1, 1, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (56, 56, 2, 1, 2, 78)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (57, 57, 3, 1, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (58, 58, 4, 1, 4, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (59, 59, 5, 1, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (60, 60, 6, 1, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (61, 61, 1, 1, 1, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (62, 62, 2, 1, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (63, 63, 3, 1, 3, 91)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (64, 64, 4, 1, 4, 67)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (65, 65, 5, 1, 5, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (66, 66, 6, 1, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (67, 67, 1, 1, 1, 82)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (68, 68, 2, 1, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (69, 69, 3, 1, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (70, 70, 4, 1, 4, 73)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (71, 71, 5, 1, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (72, 72, 6, 1, 6, 84)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (73, 73, 1, 1, 1, 80)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (74, 74, 2, 1, 2, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (75, 75, 3, 1, 3, 92)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (76, 76, 4, 1, 4, 75)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (77, 77, 5, 1, 5, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (78, 78, 6, 1, 6, 86)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (79, 79, 1, 1, 1, 83)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (80, 80, 2, 1, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (81, 81, 3, 1, 3, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (82, 82, 4, 1, 4, 72)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (83, 83, 5, 1, 5, 77)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (84, 84, 6, 1, 6, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (85, 85, 1, 1, 1, 81)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (86, 86, 2, 1, 2, 78)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (87, 87, 3, 1, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (88, 88, 4, 1, 4, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (89, 89, 5, 1, 5, 76)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (90, 90, 6, 1, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (91, 91, 1, 1, 1, 85)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (92, 92, 2, 1, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (93, 93, 3, 1, 3, 91)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (94, 94, 4, 1, 4, 67)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (95, 95, 5, 1, 5, 74)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (96, 96, 6, 1, 6, 88)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (97, 97, 1, 1, 1, 82)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (98, 98, 2, 1, 2, 79)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (99, 99, 3, 1, 3, 90)
  INTO enrollment (id, student_id, course_id, classroom_id, teacher_id, marks) VALUES (100, 100, 4, 1, 4, 75)
SELECT * FROM DUAL;



